config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get '/tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])

  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class='container mt-5'>
  <h2>Edit <%=@task.title%></h2>

  <%= form_with model: @task do |f| %>
  <div class='form-group'>
    <%= f.label :title%>
    <%= f.text_field :title, class:'form-control mt-3'%>
  </div>
  <div class='form-group'>
    <%= f.label :details %>
    <%= f.text_field :details, class:'form-control mt-3'%>
  </div>
  <div>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
    <%= f.submit class: 'btn btn-primary mt-3'%>
    <% end %>

    <hr class="mt-1 mb-1"/>

  <div>
    <%=link_to "Back to list", tasks_path%>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1>My tasks</h1>

  <ul class="row col-sm-3">
    <% @tasks.each do |task| %>
        <li>
            <%if task.completed? %>
              <i class="fa-regular fa-square-check"></i>
            <% else %><i class="fa-regular fa-square"></i>
            <% end %>
            <%= link_to task.title, task_path(task.id)%>
                <a style= text-decoration: none></a>
            <%= link_to task_path(task.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>

              <i class="fa-solid fa-trash"></i>
            <% end %>
        </li>
    <% end %>
  </ul>

  <hr class="mt-1 mb-1"/>

    <%=link_to "Create a new task", tasks_new_path, class:'btn btn-primary mt-3'%>
</div>

app/views/tasks/new.html.erb
<div class='container mt-5'>
  <h2>New Task</h2>

  <%= form_with model: @task do |f| %>
    <div class='form-group'>
      <%= f.label :title %>
      <%= f.text_field :title, class:'form-control mt-3' %>
    </div>
    <div class='form-group'>
      <%= f.label :details %>
      <%= f.text_field :details, class:'form-control mt-3'%>
    </div>
    <div class='form-group'>
      <%= f.label :completed %>
      <%= f.check_box :completed %>
    </div>
      <%= f.submit class:'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class='container mt-5'>
  <h1>Task <%=@task.title%></h1>
  <p><%=@task.details%></p>
<ul>
  <% if @task.completed? %>
    <li>
      <i class="fa-regular fa-square-check"></i><p>Task completed</p>

    </li>
  <% else %>
    <li>
      <i class="fa-regular fa-square"></i>
      <p>Task not yet completed</p>
    </li>
  <% end %>
   <%= link_to "Edit this task", task_edit_path(@task.id), class:'btn btn-primary mt-3'%>
</ul>

<hr class="mt-1 mb-1"/>

  <div>
    <i class="fa-duotone fa-hand-back-point-left"></i>
    <%=link_to "Back to list", tasks_path %>
      <a style= "text-decoration: none href=#"></a>
  </div>

</div>